### ISSUE TITLE
FTBUltiminePlugins require all canUltimine to be true

### ISSUE THREAD

**Issue by RoyalReject** [FTBTeam/FTB-Ultimine#110]
When creating plugins for FTBUltimine it requires all loaded plugins canUltimine method to evaluate to true, I believe this should be updated to check if any of them are true, this will allow multiple plugins to be loaded at once to give different ways to enable FTBUltimine

**Comment by MaxNeedsSnacks** [comment]
(FWIW, I'll probably change this to be based on InteractionResults, which have PASS (defer), FAIL (force deny) and SUCCESS (force allow))
