### ISSUE TITLE
[Feature Request] Keybind toggle for Merge Stone

### ISSUE THREAD

**Issue by medtryx** [FTBTeam/FTB-Ultimine#18]
A keybind to toggle the "merge_stone" config option would be quite handy. Most of the time, I prefer it to mine all  stone like blocks; it would be handy however, to disable this temporarily if you were wanting to harvest large amounts of stone like blocks such as the marble that is added by various mods.

**Comment by MaxNeedsSnacks** [comment]
Merging into #75, this is planned, but there are still some minor roadblocks in the way
