### ISSUE TITLE
[1.16.1]Setting hotkey to shift breaks shape change

### ISSUE THREAD

**Issue by theboo** [FTBTeam/FTB-Ultimine#19]
If you set the hotkey for ultimine to shift/sneak, it will not let you change the shape since that requires hotkey+shift+scroll.. I can see how allowing shift+scroll without another hotkey wouldn't work well as a lot of other mods' items use this for mode changes, but what about a configurable hotkey for shape change with the default being shift+scroll?

**Comment by MaxNeedsSnacks** [comment]
Merging this into #36, a keybind to change shapes is planned (actually, there's a stale PR for it already), but it's gonna be difficult to implement cross-platform
