### ISSUE TITLE
[Feature Request] Add a config options (blacklist) for blocks you don't want to get ultimined.

### ISSUE THREAD

**Issue by Gbergz** [FTBTeam/FTB-Ultimine#20]
Title^
Great mod by the way!

**-** Gbergz

**Comment by honbee** [comment]
This would be fantastic. I find it frustrating when players in my server can shapelessly mine huge chunks of stone, dirt, sand etc. It would be nice if there was a way to configure it like that.

**Comment by xenoflot** [comment]
+1 for a blacklist.  Highly desirable for skyblock maps.

**Comment by CuboidDroid** [comment]
Another +1 for blacklist

**Comment by BigAl607** [comment]
Definitely a +1 from me as well. Would love a way to make it so it can only mine ores

**Comment by MaxNeedsSnacks** [comment]
I'll probably be creating tags to allow / disallow blocks from being ultimined, for which server admins can then set the default behaviour (if a block doesn't have either tag) in the server config

**Comment by MaxNeedsSnacks** [comment]
Lat made a tag for this about 2 weeks ago, you can now use `#ftbultimine:excluded_blocks` to exclude blocks from being ultimined
