### ISSUE TITLE
[Bug] [1.16.1] Lag When Placing Blocks

### ISSUE THREAD

**Issue by medtryx** [FTBTeam/FTB-Ultimine#21]
Placing a block with Ultimine installed causes noticeable server lag.

I was able to recreate this issue with only Forge and Ultimine installed. (forge-1.16.1-32.0.93-universal.jar and ftb-ultimine-1.1.0.6.jar)  Also tested in forge-1.16.1-32.0.81-universal.jar. The pack I describe below was running forge-1.16.1-32.0.75-universal.jar, however I did not test that one in isolation. 

This was tested without activating the key for Ultimine. 

I first noticed this in a custom modpack running several mods. It is most noticeable when placing an offhand torch with a pick or weapon in the main hand. The block is rendered momentarily then disappears before reappearing. Doing this in an unlit room causes it to be way more noticeable as the light is applied removed, and reapplied. There are lighting updates from the initial placing and removal. If a lighting overlay is visible it will also update with the light flash. 

Also I noticed when placing blocks from my main hand quickly there will be significant server lag. If you have a display such as One Probe you are able to see the "waiting for server" message and some blocks will not actually place. If you pause after a short run, you can see the item count update on your hotbar. 

Removing Ultimine eliminated both issues.

**Comment by MaxNeedsSnacks** [comment]
Should be solved in 1.16.5 releases of Ultimine
