### ISSUE TITLE
Doesn't work via servers

### ISSUE THREAD

**Issue by Lou34964** [FTBTeam/FTB-Ultimine#22]
Mod seems to work perfectly fine on the client-side,
on a server it seems to not want to function. pressing grave and shift + scroll causes the UI to disappear and the blocks only mine 1 at a time.

**Comment by TheDeviantCrafter** [comment]
It works fine on my server, running Minecraft 1.16.1.

**Comment by chickenblue** [comment]
> Mod seems to work perfectly fine on the client-side,
> on a server it seems to not want to function. pressing grave and shift + scroll causes the UI to disappear and the blocks only mine 1 at a time.

got same Problem.

yesterday it was still fine. Today no more veinmining on server ui to adjust the form disappeared.

Tried everything, but just doesn't work on the server anymore

**Comment by NHCowboy** [comment]
Same, TurnKeyMineOS Forge 35.1.4 rejected from server side at startup, in game UI shows but no function.

**Comment by NHCowboy** [comment]
> It works fine on my server, running Minecraft 1.16.1.

Got time to throw a 16.4Forge server up for a test?

**Comment by Unerismy** [comment]
im receiving a non matching red x from my server i run, despite using the exact same version of ultimine and cloth api. forge 1.16.5

**Comment by MaxNeedsSnacks** [comment]
> im receiving a non matching red x from my server i run, despite using the exact same version of ultimine and cloth api. forge 1.16.5

The red X itself isn't a big deal, it just means some clientside mod didn't mark themselves as clientside correctly (or the server contains additional serverside mods that didn't mark themselves as serverside correctly)
