### ISSUE TITLE
Block outlines breaking the further you go out

### ISSUE THREAD

**Issue by thisis2838** [FTBTeam/FTB-Ultimine#23]
Block outlines become more jittery and jittery the further you go out from the world center, presumably from floating point precision errors.

**Comment by MaxNeedsSnacks** [comment]
This is most likely related to vanilla VoxelShape rendering, as it also tends to glitch out when far away from the world center.
I'll see whether there's an easy way to fix this, but otherwise, I'd just recommend to disable outlines if they get too quirky

**Comment by MaxNeedsSnacks** [comment]
While this was related to VoxelShape rendering, the issue was on our end since we just used large floats (on the order of millions) instead of translating them relative to the origin block position **first**, should be fixed in the newer releases ^^
