### ISSUE TITLE
[Feature Request/Is This A Feature] Adding tools to the list of usable tools (Skyfactory 3)

### ISSUE THREAD

**Issue by Waterspark63** [FTBTeam/FTB-Ultimine#24]
I don't know if I'm just missing the config/command to do this or not, but is it (planned/possible) to add tools/blocks to what can be mined, I'm playing SkyFac3, and I can't chain mine Compressed Cobblestone with the Compressed Stone Hammer. Again, I couldn't find anything that confirmed or denied that there was a way to customize the tool/block list, so if I missed it, and it is possible, I apologize for being blind. If it isn't currently supported, is that a possiblity in the future?

Mod Version: 1.3.4
MC Version: 1.10.2
Modpack: SkyFac3, 3.0.18

**Comment by MaxNeedsSnacks** [comment]
We don't support versions below 1.16 for this mod, unfortunately, but a tag exists in newer versions that allows you to specify tools to allow / deny from being used with ultimine
