### ISSUE TITLE
[1.16.1] Ultimine mining water?

### ISSUE THREAD

**Issue by NillerMedDild** [FTBTeam/FTB-Ultimine#25]
`ftb-ultimine-1.1.0.6`

**Issue**
Sometimes when veinmining underwater sand, only one block of sand drops and the water blocks around it disappear, but only clientside, as you still take breathing damage if you stay in. Logging out and back in resyncs the water but doesn't drop the sandblocks you were supposed to get.

![image](https://user-images.githubusercontent.com/51674867/90387749-04906480-e087-11ea-97d1-7ffca2581df8.png)

**Logs**
Server log doesn't show anything suspicious, neither does client log

**Comment by LatvianModder** [comment]
👀

**Comment by Darkere** [comment]
I believe this has a high chance of being caused by the mod Pretty Beaches.
