### ISSUE TITLE
Constant massive lag spikes running Ultimine?

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [FTBTeam/FTB-Ultimine#27]
https://spark.lucko.me/#mFZpWY9W0B

Using 1.1.0.6 as no other version for 1.16.1 is available (running the Enigmatica 6 modpack on `0.2.16` currently).
There seems to be steady low TPS even while nobody is actively harvesting anything with FTB Ultimine, and as you can tell by the Spark profile all sufficiently laggy ticks (over 200ms) seem to have been mainly caused by Ultimine's onRightClick hook. For reference, the radius in Enigmatica 6 is 128 blocks, but I will be bumping it down to 64 blocks just to see whether that fixes things. Either way, something seems ***very*** off

**Comment by A-UNDERSCORE-D** [comment]
Seems to be caused by an OnBlockBreak handler running the shapeless search on every break. At least in 1.12.2
![Screenshot from 2020-10-04 01-33-40](https://user-images.githubusercontent.com/21071450/95003911-c3c3bf00-05e4-11eb-868a-200f8de28555.png)

**Comment by MaxNeedsSnacks** [comment]
Shape walking should no longer be as laggy as it was when I made this issue, closing
