### ISSUE TITLE
FTB-Ultimine mouse scrolling doesn't work on Mac OS

### ISSUE THREAD

**Issue by adammbaker** [FTBTeam/FTB-Ultimine#29]
Holding Shift while mouse-scrolling does not change the mining method.

What I'm running:
All The Mods 6 - ATM 6 - 1.16.3 version 1.1.2 running Forge 34.1.16
Mac OS Catalina 10.15.7

**Comment by MathiasDeWeerdt** [comment]
Same problem on big sur.

**Comment by MathiasDeWeerdt** [comment]
Made a PR to add arrow up/down key to toggle shapes.
https://github.com/FTBTeam/FTB-Ultimine/pull/30

**Comment by MaxNeedsSnacks** [comment]
Merging into #59
