### ISSUE TITLE
[1.16.3-Feature Request] Add a configurable option for the merge feature in the config.

### ISSUE THREAD

**Issue by Gbergz** [FTBTeam/FTB-Ultimine#31]
Title^

Like what what blocks that should be merged together.

Currently have a modpack together with dense ores (compact ores) and when ultimining a Coal Ore vein the Compact Ore one won't follow like stone & andesite would etc.

**-** Gbergz

**Comment by Drunkender** [comment]
Same issue with integrated dynamics menril trees. Perhaps adding what block tags should be mined together.

**Comment by MaxNeedsSnacks** [comment]
> Same issue with integrated dynamics menril trees. Perhaps adding what block tags should be mined together.

This was exactly what I was planning to add in a future release, I just haven't found the time to do so with uni and other projects on the side, unfortunately

**Comment by MaxNeedsSnacks** [comment]
Merging tags has been implemented in the new release version ^^

**Comment by Glitched94** [comment]
> > Same issue with integrated dynamics menril trees. Perhaps adding what block tags should be mined together.
> 
> This was exactly what I was planning to add in a future release, I just haven't found the time to do so with uni and other projects on the side, unfortunately



> Merging tags has been implemented in the new release version ^^

In the .toml config files I can find the lines
> #Doesn't stop at different types of stones
> merge_stone = true

but the feature described and commented on in the first quote I don't necessarily see a config option for. I'd really like to add all of the other stone variants and stone-like blocks to the merge group of stone (Deepslate from Quark, all of the BYG stones, etc)

I do see a .snbt file generated, but all it contains is
> { } 
and so I was curious if somehow this was related to that grouping you mentioned wanting to implement?
