### ISSUE TITLE
Ultimine for MC 1.16.3 "Veinmining Water"

### ISSUE THREAD

**Issue by ArcheonMC** [FTBTeam/FTB-Ultimine#32]
When using ultiminer to veinmine sand blocks near/under water will cause the water to "disappear" creating a fake air pocket that can be walked around in but still has the effects of being underwater aka drowning you......

**Comment by PurpleHel** [comment]
Having what I think is the same problem, on 1.16.4, with  ftb-ultimine-1603.1.1.13. Seems to happen with any underwater block, sand, gravel, dirt, clay, and doesn't seem to matter if mining with a tool or empty hand. And the block that was aimed at doesn't mine, just the water does.
https://imgur.com/a/KVrD0p0

**Comment by MaxNeedsSnacks** [comment]
Duplicate of #
25
