### ISSUE TITLE
No hotkey to change outline changes - Shift scroll does absolutely nothing

### ISSUE THREAD

**Issue by FRojas1** [FTBTeam/FTB-Ultimine#47]
Hello, I don't really understand the decision to remove the option to use a hotkey to change the shape but regardless, shift scroll does nothing. Mod doesn't work offline or online, I really need help.

**Comment by MaxNeedsSnacks** [comment]
If you're using Mac, see #59.

We're working on keybinds to change shapes, but that may take a while to do still as we need to support this on **both** mod loaders
