### ISSUE TITLE
No option to change keybinding in controls

### ISSUE THREAD

**Issue by Fiskpung** [FTBTeam/FTB-Ultimine#56]
In minecraft 1.16.5 i dont have any option to change keybinding

**Comment by mrvn** [comment]
Same here with MultiMC, Minecraft 1.16.4 and there mods:

Mods:
  [✔️] BBOutlineReloaded-2.4-1.16.3-fabric
  [✔️] carpet-extra-1.16.3-1.4.11
  [✔️] fabric-carpet-1.16.4-1.4.21+v201216
  [✔️] ftb-ultimine-1603.1.1.14
  [✔️] malilib-fabric-1.16.4-0.10.0-dev.21+arne.2
  [✔️] minihud-fabric-1.16.4-0.19.0-dev.20201103.184029
  [✔️] skyblock-fc-1.16.4-1.2.1

The mod plain don't work.

**Comment by MaxNeedsSnacks** [comment]
@mrvn there is currently no version of ftb ultimine for fabric yet, that's a pending pr at #58

**Comment by MaxNeedsSnacks** [comment]
Also @Fiskpung it should be under "Gameplay" currently, will be moved to its own category at some point tho

**Comment by blizzy13346** [comment]
Can someone tell me what the keybind to turn on ultimine because I’ve been looking for hours and still have not found it

**Comment by blizzy13346** [comment]
@MaxNeedsSnacks 👆🏻

**Comment by MaxNeedsSnacks** [comment]
The default key should be grave on an english keyboard (`)

**Comment by MaxNeedsSnacks** [comment]
The default key on a standard QWERTY keyboard should be the grave key or `, which is to the left of the 1
