### ISSUE TITLE
Shape change does not work

### ISSUE THREAD

**Issue by LiamInfintity** [FTBTeam/FTB-Ultimine#59]
when i try to change the shape nothing happens!
i do everything it says and it doesnt work

i use mac btw

**Comment by MaxNeedsSnacks** [comment]
(See #29)

Shift + Scrolling doesn't seem to properly work on Mac, this is more of a Minecraft issue than Ultimine specifically, but as a semi-fix / workaround for this, check out #30 (TL;DR, while ultimine is open, press arrow up / down to switch shapes)

**Comment by LiamInfintity** [comment]
You mean the up/down arrow keys? Because they didnt work for me.

**Comment by MaxNeedsSnacks** [comment]
Can you try again with the latest version? Keep in mind the arrow keys only work *while* Ultimine is active (while that overlay in the top left corner is visible), plus you still need to press Shift as far as I'm aware.

(So Shift + Up Arrow or Shift + Down Arrow, I might change this though to not require the Shift key)

**Comment by MaxNeedsSnacks** [comment]
Closing as the Shift + Arrow Key thing **should** have hopefully fixed this
