### ISSUE TITLE
Version 1605.2.0 crash on dedicated server

### ISSUE THREAD

**Issue by Dunkmania101** [FTBTeam/FTB-Ultimine#62]
Version 1605.2.0 crashes my server on boot. My client loads just fine. It looks like the WorldRenderer class is being called outside of the client dist.

[Crash Log](https://gist.github.com/Dunkmania101/499365acdb12374be7f25ce88c89b056)

**Comment by MaxNeedsSnacks** [comment]
Whoops, yea, that should be in the client-only block, hold on
