### ISSUE TITLE
Crash upon startup on fabric ver 1.16.5

### ISSUE THREAD

**Issue by Moglibogli** [FTBTeam/FTB-Ultimine#65]
[crash log](https://pastebin.com/REBprk0H)

**Comment by MaxNeedsSnacks** [comment]
God damnit, messed up the buildscript...

Can you try this jar?

https://cdn.discordapp.com/attachments/794742192392110110/813440471749230642/ftb-ultimine-1605.2.0-build.9999-fabric.jar

**Comment by Moglibogli** [comment]
ok thank you this one works!
