### ISSUE TITLE
same as #65 but on forge crash on start

### ISSUE THREAD

**Issue by Staegrin** [FTBTeam/FTB-Ultimine#66]
java.lang.NoClassDefFoundError:com/feed_the_beast/mods/ftbultimine/FTBUltimine

crashlog: https://gist.github.com/Staegrin/2302a77f72809d27a7775dfb30fcd0c5

**Comment by MaxNeedsSnacks** [comment]
Same here, can you try this build? https://cdn.discordapp.com/attachments/794742192392110110/813443836838805554/ftb-ultimine-1605.2.0-build.9999-forge.jar

**Comment by Staegrin** [comment]
That fixed it. Thanks for the speedy reply.
