### ISSUE TITLE
[1.16.5] Missing check for whether the player is connected to a server

### ISSUE THREAD

**Issue by NillerMedDild** [FTBTeam/FTB-Ultimine#70]
Original issue: NillerMedDild/Enigmatica6#1409

According to Shedaniel, FTB Ultimine forgets to check if it's connected to a server before sending a server packet. This can cause a crash as reported here: https://github.com/architectury/architectury-api/issues/47

### Crash
https://pastebin.com/c59HnAJT

### Offending Code
https://github.com/FTBTeam/FTB-Ultimine/blob/28a59b55689983a8df7df586df787ec4f6b00634/common/src/main/java/com/feed_the_beast/mods/ftbultimine/client/FTBUltimineClient.java#L225

**Comment by MaxNeedsSnacks** [comment]
Should be solved in build 22 from earlier today!

**Comment by NillerMedDild** [comment]
Thanks Max!
