### ISSUE TITLE
Keeps on failing to load.

### ISSUE THREAD

**Issue by Zuelex** [FTBTeam/FTB-Ultimine#71]
I can't get into my survival world or get into the menu, cause it keeps on giving me an error everytime I try to.
![image](https://user-images.githubusercontent.com/79642290/109152517-86aec380-7763-11eb-9aa3-c40c9d89a804.png)

Please help.

**Comment by MaxNeedsSnacks** [comment]
What build of Ultimine are you using?
The latest one is ftb-ultimine-1605.2.0-build.21-forge.jar and doesn't have this issue iirc

**Comment by LatvianModder** [comment]
Try build 22

**Comment by Elpximso** [comment]
I get this with the latest version. 22

**Comment by MaxNeedsSnacks** [comment]
Do you have Architectury installed?

**Comment by Elpximso** [comment]
Me? i do

**Comment by Zuelex** [comment]
> Do you have Architectury installed?

**Comment by Zuelex** [comment]
Oh idk what i just did, im new to this i think i just closed something sorry!!

**Comment by Zuelex** [comment]
And yes im running Architectury  and im running the 22 version

**Comment by Elpximso** [comment]
Okay apparently i was missing a Architectury update, now the latest ultimine works

**Comment by Zuelex** [comment]
> Okay apparently i was missing a Architectury update, now the latest ultimine works

Same dude, i just installed the latest one and it worked
