### ISSUE TITLE
"max_blocks" config not working

### ISSUE THREAD

**Issue by itsTort** [FTBTeam/FTB-Ultimine#74]
I currently have this set to 7 on my server, however we are doing some testing -- I am getting 20-30 blocks deep with a "Small Tunnel".

**Comment by MaxNeedsSnacks** [comment]
What version of Ultimine are you currently using, and which config file are you editing, if you don't mind? We recently migrated to Jankson (.json5) for our config file format

**Comment by itsTort** [comment]
Forge - "ftb-ultimine-1605.2.0-build.22-forge.jar". It came pre-loaded with ATM6: Slice of Pi 2.  So it looks like ATM is 1 version behind, looks like you guys are at .23

The config is \config\ ftbultimine-common.toml, changing the

#Range: 1 ~ 32768
max_blocks = # (which I set to 7)

sorry for the lack of detailed reports. It was late, and I just launched a server last night, so my head was all over the place doin damage control.

**Comment by MaxNeedsSnacks** [comment]
ATM being one version behind is fine, but that .toml file doesn't do anything anymore. Realistically, I should just delete it automatically on startup, but yeah... edit the .json5 file instead, the config key there is maxBlocks
