### ISSUE TITLE
Enderman causes player to freeze in midair with some blocks

### ISSUE THREAD

**Issue by RGFTheCoder** [FTBTeam/FTB-Ultimine#76]
When the player uses the enderman pet to teleport somewhere, If it tries to teleport on a snow layer block, the player is stuck floating and can't look around, until they relog.

**Comment by MaxNeedsSnacks** [comment]
Is this an Inventory Pets issue? This is the issue tracker for FTB Ultimine.

https://github.com/capnkirok/Inventory-Pets
