### ISSUE TITLE
[Feature Request] Config option to prevent breaking by hand

### ISSUE THREAD

**Issue by DereC4** [FTBTeam/FTB-Ultimine#77]
This would be a good veinminer for my modded server but I would like players to not be able to simply break a bunch of blocks by hand and instead have to use the appropriate tool (they can easily grief hand-breakable blocks such as grass and dirt)

If there is already a way to do this in the config I apologize for my ignorance.

**Comment by MaxNeedsSnacks** [comment]
Duplicate of #53

**Comment by MaxNeedsSnacks** [comment]
From that issue:
> https://github.com/FTBTeam/FTB-Ultimine/issues/53#issuecomment-790628036
