### ISSUE TITLE
Not Working on my Server

### ISSUE THREAD

**Issue by GT-ARGO** [FTBTeam/FTB-Ultimine#78]
Im probably missing something really obvious here but every time I try to run my server when Ultimine is in the mods folder it just crashes and kills the launch of the server? Does anyone know why?
![image](https://user-images.githubusercontent.com/81055899/111889208-5f05f080-89db-11eb-877a-3d3d7a7da010.png)

**Comment by MaxNeedsSnacks** [comment]
Do you have Architectury API installed?

**Comment by GT-ARGO** [comment]
Had tto update my Architectury mod
