### ISSUE TITLE
[bug] Missing Lang (text.autoconfig.ftbultimine.title)

### ISSUE THREAD

**Issue by Brittank88** [FTBTeam/FTB-Ultimine#81]
`Forge 36.1.16`
`FTB Ultimine (Forge) 1605.2.2-build.4`

**How to reproduce the issue**

1. Open the FTB Ultimine config from the mods menu:

![image](https://user-images.githubusercontent.com/24266948/121321880-d8194200-c951-11eb-8215-adddf20464a4.png)

**Comment by MaxNeedsSnacks** [comment]
We're no longer using autoconfig, so this should be fine now ^^
