### ISSUE TITLE
Minecraft 1.17 Update

### ISSUE THREAD

**Issue by sllverx** [FTBTeam/FTB-Ultimine#84]
The new minecraft version 1.17 is out. I've been using the ultimine mod on its own rather than the whole All-in-one pack on curseforge. Since I've been playing the latest version, I was wondering if there's a way the team can update it for use in the latest version of minecraft? This mod saved so much time and made things much easier.

Hope all is well,

sllverx

**Comment by MichaelHillcox** [comment]
Once forge 1.17 is out we’ll start looking at updating our mods

**Comment by sllverx** [comment]
Awesome! Thanks!

**Comment by tankyap** [comment]
@MichaelHillcox 
but btw,the forge 1.17 is out now.Would you continue to update it?
