### ISSUE TITLE
[bug] Sever Crash 

### ISSUE THREAD

**Issue by CKY-** [FTBTeam/FTB-Ultimine#86]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod & Pack version**
0.41.pre7 
**Forge / Fabric version, if applicable**
forge: 36.1.58

**Modpack (with version), if applicable**

**If the issue is a crash; An external link to the crash report**
https://gist.github.com/CKY-/3f8111ade1e4c0c066ab51da868afc53

**How to reproduce the issue**
*Please provide use with a step by step description*
updated on server pack both Linux and Windows server 

**A screenshot, if applicable**

**Anything else we should know?**

OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

**Comment by MaxNeedsSnacks** [comment]
You're running an old version of FTB GUI Library with a new version of FTB Ultimine. Please downgrade Ultimine for now, I seem to have published it as a release accidentally
