### ISSUE TITLE
[feature]  When will it be avalabile on 1.17.1?

### ISSUE THREAD

**Issue by PaulAndreiRO** [FTBTeam/FTB-Ultimine#87]
When will it be avalabile on 1.17.1?   
 Please update the mod asap!

**Comment by MichaelHillcox** [comment]
No time soon from my understanding, sorry.

**Comment by PaulAndreiRO** [comment]
yea me too.... :(

**Comment by MaxNeedsSnacks** [comment]
See https://github.com/FTBTeam/FTB-Quests/issues/619#issuecomment-901976398, we probably won't be pushing out a 1.17 build as Mikey already said, but **if** we do end up changing our minds, I'll keep you posted obviously!
