### ISSUE TITLE
I don't know how to 'activate' FTB Ultimine

### ISSUE THREAD

**Issue by LilianaFlower** [FTBTeam/FTB-Ultimine#88]
Mod Version: 1605.3.0-build.21

All The Mods 6 1.7.6

I don't know how to replicate the issue.
I was just playing and working on stuff when I realized that FTB Ultimine said 'FTB Ultimine is not active' in the top left when I tried to use it. 

![2021-08-02_14 44 44](https://user-images.githubusercontent.com/88306376/127915150-4b4a81cb-4bb9-46a8-aaa2-ae75e5a7608b.png)

I know this isn't a bug because my friend's Ultimine is still active, but I have no clue how to reactivate mine. Please help me.

**Comment by MaxNeedsSnacks** [comment]
You're holding an Ars Nouveau spell book in your off hand, which disables Ultimine to prevent issues with the "Break" spell ^^

In the future, we'll have more detailed error messages; just know that that's why you can't use Ultimine right now
